backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title (EN)", name: "title_en", widget: "string" }
      - { label: "Title (ZH)", name: "title_zh", widget: "string" }
      - { label: "Year", name: "year", widget: "string" }
      - { label: "Body (EN)", name: "body_en", widget: "markdown" }
      - { label: "Body (ZH)", name: "body_zh", widget: "markdown" }
      - { label: "Images", name: "images", widget: "image", multiple: true }
